#
#   Makefile.fpc for Free Pascal Android/JVM (Dalvik) RTL
#

[package]
main=rtl

[target]
loaders=
units=$(SYSTEMUNIT) $(UUCHARUNIT) $(OBJPASUNIT) $(LNFOJVMUNIT) $(ANDROIDR14UNIT) $(SYSUTILSUNIT) $(SYSCONSTUNIT)

[require]
nortl=y

[install]
fpcpackage=y

[default]
fpcdir=../../..
target=android

[compiler]
includedir=$(INC) $(PROCINC)
includedir_jvm=../../java
sourcedir=$(INC) $(PROCINC) $(COMMON) $(ARCH)
sourcedir_jvm=../../java

[prerules]
RTL=../..
INC=$(RTL)/inc
COMMON=$(RTL)/common
PROCINC=$(RTL)/$(CPU_TARGET)
UNITPREFIX=rtl
SYSTEMUNIT=system
OBJPASDIR=$(RTL)/objpas

ifdef RELEASE
override FPCOPT+=-Ur
endif

CPU_UNITS=
SYSINIT_UNITS=

[rules]
.NOTPARALLEL:

.PHONY: installclasses

installclasses:
	$(MKDIRTREE) $(INSTALL_UNITDIR)/org/freepascal/rtl
ifdef inUnix
        $(INSTALL) $(subst $$,\$$, $(wildcard $(UNITTARGETDIRPREFIX)/org/freepascal/rtl/*.class)) $(INSTALL_UNITDIR)/org/freepascal/rtl
else
        $(INSTALL) $(wildcard $(UNITTARGETDIRPREFIX)/org/freepascal/rtl/*.class) $(INSTALL_UNITDIR)/org/freepascal/rtl
endif

fpc_install: installclasses


# Get the system independent include file names.
# This will set the following variables :
# SYSINCNAMES
include $(INC)/makefile.inc
SYSINCDEPS=$(addprefix $(INC)/,$(SYSINCNAMES))

# Get the processor dependent include file names.
# This will set the following variables :
# CPUINCNAMES
include $(PROCINC)/makefile.cpu
SYSCPUDEPS=$(addprefix $(PROCINC)/,$(CPUINCNAMES))

# Put system unit dependencies together.
SYSDEPS=$(SYSINCDEPS) $(SYSCPUDEPS)


#
# Base Units (System, strings, os-dependent-base-unit)
#

$(SYSTEMUNIT)$(PPUEXT) : $(RTL)/java/$(SYSTEMUNIT).pp $(SYSDEPS)
        $(COMPILER) -Us -Sg @rtl.cfg $(RTL)/java/$(SYSTEMUNIT).pp $(REDIR)

uuchar$(PPUEXT): $(SYSTEMUNIT)$(PPUEXT) $(INC)/uuchar.pp
	$(COMPILER) $(INC)/uuchar.pp

objpas$(PPUEXT): $(RTL)/java/objpas.pp
        $(COMPILER) $(RTL)/java/objpas.pp $(REDIR)

lnfojvm$(PPUEXT): $(RTL)/java/lnfojvm.pp $(OBJPASUNIT)$(PPUEXT)
        $(COMPILER) $(RTL)/java/lnfojvm.pp $(REDIR)

androidr14$(PPUEXT): $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) androidr14.pas androidr14.inc
	$(COMPILER) androidr14.pas

#
# Delphi Compatible Units
#

sysutils$(PPUEXT) : $(RTL)/java/sysutils.pp $(wildcard $(OBJPASDIR)/sysutils/*.inc) \
                    objpas$(PPUEXT) sysconst$(PPUEXT)
        $(COMPILER) -Fi$(OBJPASDIR)/sysutils $(RTL)/java/sysutils.pp $(REDIR)
